export const ADDTODOS = 'ADDTODOS';
export const EDITTODOS = 'EDITTODOS';
export const DELETETODOS = 'DELETETODOS';
export const CONFIRMTODODS ='CONFIRMTODOS';
export const CANCELTODODS ='CANCELTODOS';

